# Dockerfile for MCP Proxy
FROM golang:1.25-alpine AS builder

WORKDIR /build

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

ARG GOARCH=amd64

# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${GOARCH} go build -o mcpproxy ./cmd/proxy

# Final stage
FROM scratch
WORKDIR /app
EXPOSE 8080 2113

COPY --from=builder /build/mcpproxy .

CMD ["./mcpproxy"]
