proxy:
  base_url: http://localhost:8080
  listen_addr: ":8080"

idp:
  client_id: 379eab96-a9ad-401f-8158-19b130fefbf3
  client_secret: supersecret123
  openid_configuration_url: https://swelfad01azne.b2clogin.com/swelfad01azne.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_HOME_REALM_DISCOVERY
  scopes:
    - openid
    - profile
    - 379eab96-a9ad-401f-8158-19b130fefbf3
  claims_mapping:
    sub: X_sub
    name: X_full_name
    email: X_email
    upn: X_upn

encryption:
  master_key: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

telemetry:
  enabled: false
  service_name: mcp-proxy
  service_version: 1.0.0
  otlp_endpoint: localhost:4318

upstream:
  name: weather-test
  resource: http://localhost:8081
  base_url: http://localhost:8081
  path_prefix: /mcp
